### ISSUE TITLE
How to use this package in pubsub for big file transport?

### ISSUE THREAD

**Issue by TianshuDing** [libp2p/go-libp2p-pubsub-router#83]
in GossipSub, there is a MessageSize limit. Someone told me to use this package to avoid bandwith waste.

**Comment by TianshuDing** [comment]
so, is there any example about this how to config this package in pubsub?  transmit a big file(>10MB)

**Comment by aschmahmann** [comment]
@TianshuDing GitHub issues are best used for things like feature requests and bug reports, discussion/support questions are better on discuss.libp2p.io since the discoverability is higher (not too many people look at closed GitHub issues for support questions). Feel free to tag me on your post and we can discuss there.
